### ISSUE TITLE
能登录，但是之后就立即卡住了。

### ISSUE THREAD

**Issue by finch-xu** [hirCodd/AutoAddProblem#1]
是不是没有找到create_problem
`D:\AutoAddProblem-master\AddProblem>python add_problem.py

DevTools listening on ws://127.0.0.1:12637/devtools/browser/a4fc5587-d233-46c0-8373-9ec024a1a88c
Traceback (most recent call last):
  File "add_problem.py", line 214, in <module>
    main()
  File "add_problem.py", line 211, in main
    handle_login()
  File "add_problem.py", line 64, in handle_login
    EC.presence_of_element_located((By.CSS_SELECTOR, '#app > div > div.content-app > div.view > div.panel > div > div.panel-options > button > span'))
  File "C:\Users\finch\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

**Comment by pq-dong** [comment]
我是在这里卡住了，作者能提供个思路吗？

**Comment by moremind** [comment]
有另一个版本，等会马上去，这个版本他们改过一次了。

**Comment by pq-dong** [comment]
> 有另一个版本，等会马上去，这个版本他们改过一次了。

嗯嗯，感谢感谢！！！

**Comment by moremind** [comment]
> > 有另一个版本，等会马上去，这个版本他们改过一次了。
> 
> 嗯嗯，感谢感谢！！！

现在更新了另一个版本add_problem_v2.py那个版本还有v1.1那个，你可以看一下。
